export enum CodigoTipoSensor {
  TEMP_HUME_AMBIENTAL = 'TEMP_HUME_AMBIENTAL',
  HUMEDAD_SUELO = 'HUMEDAD_SUELO',
  RADIACION_SOLAR = 'RADIACION_SOLAR',
  PRECIPITACION = 'PRECIPITACION',
  PH = 'PH',
}
